### ISSUE TITLE
CSV file format is not a valid format

### ISSUE THREAD

**Issue by olivierobert** [sanjib/keyword-insight#14]
## Issue

Actual comma-separated files (CSVs) are not a valid format.

![image](https://user-images.githubusercontent.com/696529/139616857-a5502c49-afa1-4f21-9d77-5b6fb203b252.png)

## Steps to reproduce

1. Go to https://keyword-insight.viaye.com/projects/add
2. Upload a csv file

**Comment by sanjib** [comment]
@olivierobert Thanks for the detailed feedback, much appreciated. Can you please provide the template.csv file that you used to test? It will be very helpful if I can also try the file you used.

**Comment by olivierobert** [comment]
The file has the following structure:

![image](https://user-images.githubusercontent.com/696529/139788311-e972e05e-0edb-473b-84a6-21a1c3f4bcbc.png)

When reviewing the code, the issue seems to stem from the list of valid file types:

https://github.com/sanjib/keyword-insight/blob/master/frontend/src/screens/ProjectAddScreen.js#L33

This would only allow `.txt` and `.xlsx` files.

**Comment by sanjib** [comment]
The file type 'application/vnd.ms-excel' on Chrome/Windows detects CSV files. Using 'text/csv' only doesn't work on Windows. Whereas on Firefox/Linux 'text/csv' works but not 'application/vnd.ms-excel'. I haven't been able to test on Mac OS however, but I think it should work on Mac as well now.

**Comment by sanjib** [comment]
The update has been deployed on the server and can be tested on https://keyword-insight.viaye.com/

**Comment by olivierobert** [comment]
I confirmed the fix on the live site 👍  Note that it would have been better to open a pull request so that it is easier to review the code changes.

**Comment by sanjib** [comment]
Thanks for the confirmation 😊 Sorry, not that up to speed with working in a team on Github. Did you mean to open a pull request after fixing each issue? My thoughts were fixing all the issues, then do a merge pull request of the fix/feedback branch.

**Comment by olivierobert** [comment]
The standard process is for each issue to be fixed by one pull request. The smaller the change to review, the easier it is. Also, Github allows to even close an issue upon merging the pull request. It requires mentioning the issue in the PR description with a keyword. Below is an example for the pull request description to close the current issue:

```
...some text describing the changes...

Solves #14

```

You can learn more on [the Github docs](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests).

> not that up to speed with working in a team on Github

Yes, I thought the same 😅
