### ISSUE TITLE
Using ENUM data type for project status

### ISSUE THREAD

**Issue by olivierobert** [sanjib/keyword-insight#18]
PostgreSQL supports [enumerated types](https://www.postgresql.org/docs/9.1/datatype-enum.html) since version 9.x. Therefore this type should be preferred over VARCHAR

https://github.com/sanjib/keyword-insight/blob/cbc287cd7243da2d9c077b9bc3ee9be15b71ee19/backend/data/db.sql?_pjax=%23js-repo-pjax-container%3Afirst-of-type%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%3Afirst-of-type%2C%20%5Bdata-pjax-container%5D%3Afirst-of-type#L21

**Comment by sanjib** [comment]
Thanks. Have altered status column to type enum. Also tested on deployed server, works well.
