### ISSUE TITLE
Image assets handling

### ISSUE THREAD

**Issue by olivierobert** [sanjib/keyword-insight#20]
The frontend application currently does not have a consistent management f image assets. Some files are in `public/`, SVG images are either inlined or placed the `src` folder. 

It is common in most React JS codebase to implement an SVG component using either [this technique](https://css-tricks.com/creating-svg-icon-system-react/) or [this one](https://www.robinwieruch.de/react-svg-icon-components). It helps to see groups all SVG images in one place and keep the HTML code more readable.

**Comment by sanjib** [comment]
- Forget to delete the logo.svg in the src folder (came from the npx create-react-app)
- Inlined "svg" have been refactored and moved to their own components similar to [this article](https://css-tricks.com/creating-svg-icon-system-react/)

**Comment by sanjib** [comment]
@olivierobert Thanks, have fixed this. If there is no further feedback, please feel free to close this issue.

**Comment by olivierobert** [comment]
Found it on the branch https://github.com/sanjib/keyword-insight/commits/fix/feedback :-)
